# Generated by Django 5.0 on 2024-01-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpId',
            field=models.CharField(max_length=5),
        ),
    ]
