# Generated by Django 5.0 on 2024-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/review/review_images/'),
        ),
    ]
