# Generated by Django 5.0 on 2024-02-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='feedback',
        ),
    ]
