# Generated by Django 5.0 on 2024-02-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0004_rename_feedback_text_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedback_text',
        ),
    ]
