# Generated by Django 5.0 on 2024-02-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0005_rename_feedback_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
