# Generated by Django 5.0 on 2024-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0006_alter_feedback_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='FeedBack',
        ),
    ]
